services:
  app:
    build: .
    container_name: tracker2-app
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - "9444:9444"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tracker2
      POSTGRES_PASSWORD: tracker2
      POSTGRES_DB: tracker2
    ports:
      - "5542:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracker2"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
