name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff lint
        run: ruff check .
      - name: Black format check
        run: black --check .
      - name: Mypy type check
        run: mypy app/core app/db app/models
      - name: Pytest
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-type-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build container image
        run: docker build -t tracker2-ci .
